### ISSUE TITLE
Why import os when working with csv file (import csv)?

### ISSUE THREAD

**Issue by Jethet** [Jethet/Address_book#13]
My test code Test_csv_print.py and two others work fine without import os.

**Comment by amrs-tech** [comment]
Please elaborate your issue because i couldn't find your test file in you repository

**Comment by Jethet** [comment]
Ehm, have I misunderstood? I thought I could save things that I want to discuss with a person working with me on this project? Do I now get responses from GitHub? I just want to check with someone why she uses import os, did not intend to bring this up with anyone else.
